name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Filter Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Install
      uses: actions/npm@master
      with:
        args: install --prefix ./website
    - name: Update version
      uses: clay/docusaurus-github-action@master
      with:
        args: version
    - name: Deploy Docs
      uses: clay/docusaurus-github-action@master
      with:
        args: deploy
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        BUILD_DIR: "website",
        PROJECT_NAME: "finos-fo"
