name: CI

on:
  push:
    branches:
    - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: npm install --prefix ./website
    - name: Update version
      uses: maoo/docusaurus-github-action@v1
      with:
        args: version
    - name: Deploy Docs
      uses: maoo/docusaurus-github-action@v1
      with:
        super_secret: ${{ secrets.DEPLOY_SSH_KEY }}
        args: deploy
      env:
        BUILD_DIR: "website"
        PROJECT_NAME: "finos-fo"
